# Generated by Django 4.0.2 on 2022-10-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0002_alter_classe_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Liste des classe'},
        ),
    ]
