# Generated by Django 4.1.1 on 2022-09-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleve', '0007_alter_eleve_date_de_naissance'),
        ('module', '0002_alter_module_nombre_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve_autoriser_composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve', verbose_name='Elève')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Liste des Elèves autorisés à composer un devoir',
            },
        ),
    ]
