# Generated by Django 4.0.2 on 2022-10-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0002_alter_module_nombre_heure'),
        ('classe', '0002_alter_classe_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classe.classe', verbose_name='Classe')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module', verbose_name='Classe')),
            ],
        ),
    ]
