# Generated by Django 4.0.2 on 2022-10-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_chaque_classe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classemodule',
            options={'verbose_name': 'Liste des module en fonction des classes'},
        ),
    ]
