# Generated by Django 4.1.1 on 2022-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifiant', models.CharField(max_length=200, unique=True, verbose_name='Identifiant du module')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du module')),
                ('nombre_heure', models.TimeField(verbose_name='Nombre heure du module')),
                ('semestre', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Liste des modules',
            },
        ),
    ]
