# Generated by Django 4.1.1 on 2022-09-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seance_cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='SeanceCours',
        ),
    ]
