# Generated by Django 4.1.1 on 2022-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance_cours', '0003_alter_seancecours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seancecours',
            name='nombre_heure',
            field=models.PositiveIntegerField(verbose_name='Nombre heure du cours'),
        ),
    ]
