# Generated by Django 4.1.1 on 2022-09-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleve', '0007_alter_eleve_date_de_naissance'),
        ('seance_cours', '0002_rename_cours_seancecours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True)),
                ('Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seance_cours.seancecours', verbose_name='Cours')),
                ('Eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve', verbose_name='Elève')),
            ],
            options={
                'verbose_name': 'Liste des cours',
            },
        ),
    ]
