# Generated by Django 4.0.2 on 2022-10-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'verbose_name': 'Liste des Absents'},
        ),
    ]
