# Generated by Django 4.0.2 on 2022-10-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0002_alter_classe_nom'),
        ('absent', '0002_alter_absent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='Classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classe.classe', verbose_name='Classe'),
        ),
    ]
