# Generated by Django 4.1.1 on 2022-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INE_eleve', models.CharField(max_length=200, unique=True, verbose_name="INE de l'élève")),
                ('nom_eleve', models.CharField(max_length=200, verbose_name="Nom de l'élève")),
                ('prenom_eleve', models.CharField(max_length=200, verbose_name="Prenom de l'élève")),
                ('date_de_naissance', models.DateTimeField(verbose_name="date de naissance de l'élève")),
                ('filiere', models.CharField(max_length=200, verbose_name="filière de l'élève")),
                ('classe', models.CharField(max_length=200, verbose_name="classe de l'élève")),
                ('est_chef', models.BooleanField(default=False, verbose_name='Est chef de classe')),
            ],
            options={
                'verbose_name': 'Liste des Elèves',
            },
        ),
    ]
