# Generated by Django 4.1.1 on 2022-09-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0003_alter_eleve_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_de_naissance',
            field=models.DateField(null=True, verbose_name="date de naissance de l'élève"),
        ),
    ]
