# Generated by Django 4.0.2 on 2022-10-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0009_eleve_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
    ]
